name: cancelable_compute
description: Spawn an isolate, run callback on that isolate, passing it message, and return the value returned by callback or canceled by user.
version: 1.2.0
homepage: https://github.com/ykmnkmi/cancelable-compute.dart
repository: https://github.com/ykmnkmi/cancelable-compute.dart
issue_tracker: https://github.com/ykmnkmi/cancelable-compute.dart/issues

environment:
  sdk: '>=2.14.0 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.18.0
