name: cancelable_compute
description: >
  Flutter-based compute operation that can be canceled with either null or a specific value.
version: 2.0.0
homepage: https://github.com/ykmnkmi/cancelable-compute.dart
repository: https://github.com/ykmnkmi/cancelable-compute.dart
issue_tracker: https://github.com/ykmnkmi/cancelable-compute.dart/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.4
