name: cancelable_compute
description: Flutter based compute operation, that can be canceled with null or with value.
version: 1.3.0
homepage: https://github.com/ykmnkmi/cancelable-compute.dart
repository: https://github.com/ykmnkmi/cancelable-compute.dart
issue_tracker: https://github.com/ykmnkmi/cancelable-compute.dart/issues

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  meta: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.21.0
